#!/usr/bin/env bash
set -euo pipefail

# Regenerates ALL_IN_ONE_MULTI_AGENT_LOOP_KIT.md from the live repo files.
#
# The all-in-one file is a flattened, read-only snapshot for pasting the whole
# kit into a single AI context window. It MUST be generated, never hand-edited,
# or it drifts from the real files. Run this after changing kit files:
#
#   bash tools/build-all-in-one.sh
#   # or: bun run build:all-in-one  /  npm run build:all-in-one

OUTPUT="ALL_IN_ONE_MULTI_AGENT_LOOP_KIT.md"

# Resolve repo root so the script works from anywhere.
if git rev-parse --show-toplevel >/dev/null 2>&1; then
  ROOT="$(git rev-parse --show-toplevel)"
else
  ROOT="$(cd "$(dirname "$0")/.." && pwd)"
fi
cd "$ROOT"

VERSION="$(grep -oE '"version"[[:space:]]*:[[:space:]]*"[^"]+"' package.json 2>/dev/null \
  | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || echo "unknown")"
GENERATED="$(date -u '+%Y-%m-%d %H:%M UTC')"

# Map file extension -> code-fence language label.
lang_for() {
  case "$1" in
    *.md|*.mdc) echo "md" ;;
    *.sh)       echo "bash" ;;
    *.json)     echo "json" ;;
    *.yml|*.yaml) echo "yaml" ;;
    *.gitignore|*/.gitignore) echo "gitignore" ;;
    *)          echo "text" ;;
  esac
}

# Pick a fence longer than the longest backtick run inside the file, so files
# that themselves contain ``` blocks nest correctly.
fence_for() {
  local file="$1" longest=0 run
  while IFS= read -r line; do
    case "$line" in
      '```'*)
        run="$(printf '%s' "$line" | sed -E 's/^(`+).*/\1/' | awk '{print length}')"
        [ "$run" -gt "$longest" ] && longest="$run"
        ;;
    esac
  done < "$file"
  local n=$(( longest + 1 ))
  [ "$n" -lt 3 ] && n=3
  printf '%*s' "$n" '' | tr ' ' '`'
}

# Collect kit files in a stable order. Include dotfiles under .cursor/.github.
# Exclude: VCS internals, the output file itself, archives, node_modules.
FILES=()
while IFS= read -r f; do
  FILES+=("$f")
done < <(
  find . \
    -path ./.git -prune -o \
    -path ./node_modules -prune -o \
    -type f \
    ! -name "$OUTPUT" \
    ! -name '*.zip' \
    -print \
  | sed 's#^\./##' \
  | LC_ALL=C sort
)

TMP="$(mktemp)"
{
  echo "# All-in-One Multi-Agent Loop Kit v${VERSION}"
  echo ""
  echo "> ⚠️ **GENERATED SNAPSHOT — DO NOT EDIT THIS FILE.**"
  echo ">"
  echo "> Built by \`tools/build-all-in-one.sh\` on ${GENERATED}."
  echo "> This is a flattened, read-only concatenation of the kit, provided only"
  echo "> for quick reading or pasting into a single AI context window."
  echo ">"
  echo "> The **canonical source is the folder structure** (\`README.md\`,"
  echo "> \`AGENTS.md\`, \`prompts/\`, \`tools/\`, \`docs/\`, etc.). Always copy and edit"
  echo "> those, then re-run the generator. Any change made here will be lost."
  echo ""
  echo "Contains ${#FILES[@]} files."
  echo ""
  echo "---"
  echo ""

  for f in "${FILES[@]}"; do
    lang="$(lang_for "$f")"
    fence="$(fence_for "$f")"
    echo "## \`${f}\`"
    echo ""
    echo "${fence}${lang}"
    cat "$f"
    # Ensure the closing fence sits on its own line even if the file lacks a
    # trailing newline.
    [ -n "$(tail -c1 "$f")" ] && echo ""
    echo "${fence}"
    echo ""
  done
} > "$TMP"

mv "$TMP" "$OUTPUT"
echo "✅ Wrote $OUTPUT (${#FILES[@]} files, v${VERSION}, ${GENERATED})."
